### ISSUE TITLE
Bert의 기본 max seq len이 512이라는 정보가 이 repo에도 영향을 주지 않는 것인지 궁금합니다.

### ISSUE THREAD

**Issue by JB0527** [ni-inha/Automatic-identification-system-for-fall-event-records-in-EMR-clinical-notes#5]
이 repo의 main.py의 max seq len이 650 입니다.
main.py에선 다음과 같이 model 디렉토리 아래 있는 pretrained된 klue의 bert 모델을 사용하고 있고, tokenizer도 이 모델에서 정의된 것을 사용하고 있는 것으로 보입니다.

다만 허깅페이스의 transformer config를 보면 max seq len이 512임을 알 수 있습니다
(다음은 kluebertbase의 config 입니다.)
![image](https://github.com/ni-inha/Automatic-identification-system-for-fall-event-records-in-EMR-clinical-notes/assets/69136398/03693846-7a00-4520-9b67-3e22b4f592dc)

(다음은 kluebertbase의 tokenizer 입니다.)
![image](https://github.com/ni-inha/Automatic-identification-system-for-fall-event-records-in-EMR-clinical-notes/assets/69136398/a8e0c521-6674-4608-9ab3-303cca798103)

일단 config는 이러합니다.  klue bert 모델의 config 파일을 보면 이미 token 갯수를 512개로 설정을 해서 사전학습이 된 것이라 해당 모델로는 512개 이상을 처리할 수 없지 않을까라는 생각을 했습니다. 

만약 이 모델처럼 maxseqlen을 650으로 set 해버리면 큰 문제가 없는지 궁금합니다. 

다음은 이와 같은 질문을 하게 된 이유인 에러메시지를 첨부하였습니다.

* MAX_SEQ_LEN 512 이상 시 오류 메시지
![image](https://github.com/ni-inha/Automatic-identification-system-for-fall-event-records-in-EMR-clinical-notes/assets/69136398/c6463d81-18c7-4af5-b72a-7816c7bfb4fb)

모델 생성 시 BertConfig 에 max_position_embeddings 설정값을 512 이상으로 주고 실행한 예시를 전달 받은 것을 가져와보았습니다. 여기선 reshape 처리 중 에러가 발생하는 것을 확인하였습니다.

**Comment by oneonlee** [comment]
MAX_SEQ_LEN 512 이상 시 오류 메시지 확인했습니다.

다만, 해당 오류 메시지가 어떤 코드에서 발생했는지에 대한 정보가 없네요.

본 repo의 'main.py'에서 MAX_SEQ_LEN을 644로 했을 때 에러가 발생했다는 말인가요?

**Comment by oneonlee** [comment]
klue-bert-base의 모델 config에서 ”max_position_embeddings” 값이 512인 것,
tolenizer config에서 “model_max_length” 값이 512인 것 확인했습니다.

—-

> klue bert 모델의 config 파일을 보면 이미 token 갯수를 512개로 설정을 해서 사전학습이 된 것이라 해당 모델로는 512개 이상을 처리할 수 없지 않을까라는 생각을 했습니다.

검증이 필요한 의견인 것 같네요.

—-

> 만약 이 모델처럼 maxseqlen을 650으로 set 해버리면 큰 문제가 없는지 궁금합니다.

이 부분에 대해선, 저도 확인해본 적이 없습니다. 
마찬가지로, tokenizer.encode를 수행할때, max_length 파라미터에  max_seq_len(650) 값을 준 후, 잘 토큰화가 되는지를 따로 검증해보세요.

또한, 그렇게 토큰화 된 input_ids 데이터가 모델 로 들어갈 때의 shape 변화를 추적해보세요.
(tensorflow보단 pytorch로 간단하게 구현하여 확인하는 것을 추천합니다)

—-

MAX_SEQ_LEN 512 이상 시 오류 메시지 확인했습니다.

다만, 해당 오류 메시지가 어떤 코드에서 발생했는지에 대한 정보가 없네요.

본 repo의 'main.py'에서 MAX_SEQ_LEN을 644로 했을 때 에러가 발생했다는 말인가요?

어떤 상황인지는 잘 모르겠지만, 개인적으로 해당 오류는 MAX_SEQ_LEN 값이 512를 초과해서 발생한 것 같지는 않습니다.

추가 정보를 자세히 제시해주시면 답변드리겠습니다.

**Comment by JB0527** [comment]
```
> MAX_SEQ_LEN 512 이상 시 오류 메시지 확인했습니다.

다만, 해당 오류 메시지가 어떤 코드에서 발생했는지에 대한 정보가 없네요.

본 repo의 'main.py'에서 MAX_SEQ_LEN을 644로 했을 때 에러가 발생했다는 말인가요?

어떤 상황인지는 잘 모르겠지만, 개인적으로 해당 오류는 MAX_SEQ_LEN 값이 512를 초과해서 발생한 것 같지는 않습니다.

추가 정보를 자세히 제시해주시면 답변드리겠습니다. @JB0527
```

일단 에러코드는 main.py와는 관련 없이 kluebert의 config 자체의 max seq len 을 644로 설정하여 한번 실험을 거친 것 같습니다. 
bert 자체의 maxseqlen이 512가 최대인지에 대한 실험이었습니다. 다만 이는 면밀한 부분이 아니라 후에 첨부해드리겠습니다.

이외의 말씀해주신 검증은 torch로 shape를 확인해보겠습니다.  확인 후 이에 관한 실험결과를 알려드리겠습니다.

도움을 주셔서 감사합니다.

**Comment by JB0527** [comment]
각 layer에 입력되는 token을 reshape해서 tensor도 찍어봤더니 encoder에도 decoder에도 모두 잘 담기는 것을 확인했습니다.
일단 그 이유로는 이 코드자체의 문장길이를 650으로 제한되어있으며, 한국어의 형태소상 문장 길이가 650이면 거진 (bertoknizer기준) 400이하의 토큰이 나옵니다. 고로 512 제한을 넘지 않는 것입니다. 
![image](https://github.com/ni-inha/Automatic-identification-system-for-fall-event-records-in-EMR-clinical-notes/assets/69136398/1cd273b9-2afd-43af-a2a6-bdf327226b3a)

논문자체의 포지서녈 임베딩 레이어의 수학적 공식을 보면 다음사진과 같습니다.

pos는 단어의 인덱스이며, 대부분의 문장에서 일반적인 길이를 포함하는 척도로 10000을 설정했습니다. 이제 이러한 함수의 시각화를 살펴보면 pos 값이 10000보다 작을 때까지 각 단어의 고유한 시간적 표현을 얻을 수 있음을 알 수 있습니다. 그러나 일단 길이가 10000보다 크면 표현은 각 단어마다 고유하지 않을 것으로 보이고 따라서 만약 max_length = scale (여기선 논의된 512) 및 sequence_length > max_length 의 포지서녈 인코딩이 작동하지 않을 것이라고 이론적으론 그러합니다.

물론 BERT가 어떤 scale value를 내는진 정확하게 모르지만, 또 512개까지 알아서 잘라서 토큰을 넣을지도 모르지만 제 생각은 이것과 같고, 코드에서 실험적으론 1800길이? 토큰이 약 900개인 경우도 담기긴했습니다. 이론적 배경은 이러하나 코드자체는 가능할지도 모르긴하였습니다.

일단 이 repo에선 큰 문제가 없으며, 다른 문제도 이와 같은 문제가 아님(sql이슈였음)을 판단하여 이 이슈는 해결되었습니다.
